### ISSUE TITLE
Please raise issues about checkpoints here

### ISSUE THREAD

**Issue by mzhaoshuai** [mzhaoshuai/Divide-and-Co-training#3]
Please raise issues about checkpoints here

See [checkpoints ](https://github.com/mzhaoshuai/SplitNet-Divide-and-Co-training/blob/main/miscs/checkpoints.md)

**Comment by EchoShao8899** [comment]
Hi! I want to download your model checkpoint but find that `model_best.pth.tar` cannot be extracted. It seems that the tar file is not correct. I have tried using `tar -xvf` on Linux and also the WinRAR on Windows but still cannot solve the problem.

Can you check whether the model file is okay? Or did I miss anything important? Thanks for your help.
